//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Biblioteca.Models.EntidadesBiblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosHistoricos
    {
        public int idRegistro { get; set; }
        public Nullable<int> idPregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> idAlumno { get; set; }
        public Nullable<System.DateTime> fechaRespuesta { get; set; }
        public Nullable<System.DateTime> fechaBorrado { get; set; }
    }
}
